name: Testing stuff

on:
  push:
    branches: [ main, master ]

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Test Success      
        uses: rjstone/discord-webhook-notify@v1.0.4
        if: success()
        with:
            severity: info
            details: Test Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Failure
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
            severity: error
            details: Test Failed!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Cancelled
        uses: rrjstone/discord-webhook-notify@v1.0.4
        if: cancelled()
        with:
            severity: warn
            details: Test Cancelled!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
